# Add 'bug' label to any changes to test files
bug:
  - changed-files:
    - any-glob-to-any-file: 'tests/**'

# Add 'documentation' label to any changes to documentation files
documentation:
  - changed-files:
    - any-glob-to-any-file:
      - '*.md'
      - 'docs/**'

# Add 'dependencies' label to any changes to dependency files
dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - 'requirements.txt'
      - 'pyproject.toml'
      - 'Pipfile'
      - 'poetry.lock'

# Add 'github-actions' label to any changes to workflow files
github-actions:
  - changed-files:
    - any-glob-to-any-file: '.github/workflows/**'

# Add 'source' label to any changes to source code
source:
  - changed-files:
    - any-glob-to-any-file: 'src/**'

# Add 'tests' label to any changes to test files
tests:
  - changed-files:
    - any-glob-to-any-file: 'tests/**'