name: Assign issues

on:
  issues:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      
    steps:
      - name: Assign issue to creator
        uses: pozil/auto-assign-issue@v2
        with:
          assignees: mastwet
          numOfAssignee: 1
          allowSelfAssign: true